### ISSUE TITLE
i386 compatibility

### ISSUE THREAD

**Issue by marijnvdwerf** [tpoechtrager/osxcross#271]
I can build 32-bit programs on my local machine (running 10.13). But when I dump the SDK, it dumps SDK versions 10.14. Building using this SDK doesn't allow me to build 32-bit software using osxcross.
I've tried using a distribution of the 10.13 SDK, but those have some headers (`<chrono>`) missing.

**Comment by HinTak** [comment]
I think apple stopped supporting 32-bit in their more recent os releases. I have the chrono header under 10.13 , at "v1/chrono". Those were considered "experimental" in earlier sdk / c++ standard and under "v1", etc.

**Comment by Gcenx** [comment]
@marijnvdwerf using a distribution of 10.13.SDK won’t contain those headers as those are part of Xcode and not the SDK.

You need to have a copy of Xcode_9.4.1 place into a sub directory then set `XCODEDIR` to the directory that contains it then run `gen_sdk_package.sh` and this will produce a working 10.13.SDK.

The reason your able to still compile 32Bit with Xcode_10 is due to macOS High Sierra still providing full headers in `/usr/include`, this is no longer the case in future macOS versions.

**Comment by marijnvdwerf** [comment]
Thanks!
